name: Build AMDVLK for LLPC

on:
  workflow_dispatch:

jobs:
  build-and-push-amdvlk:
    name: "Features: ${{ matrix.feature-set }}"
    runs-on: ${{ matrix.host-os }}
    strategy:
      fail-fast: false
      matrix:
        host-os:        ["ubuntu-20.04"]
        image-template: ["gcr.io/stadia-open-source/amdvlk_%s%s:nightly"]
        branch:         [dev]
        config:         [Release]
        feature-set:    [+clang+shadercache+tsan]
        generator:      [Ninja]
    steps:
      - name: Free up disk space
        run: |
          echo 'Before:' && df -h
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/hostedtoolcache/boost /opt/ghc
          echo 'After:' && df -h
      - name: Checkout LLPC
        run: |
          git clone https://github.com/${GITHUB_REPOSITORY}.git .
          git checkout ${GITHUB_SHA}
     
      - name: Generate Docker image tag string
        run: |
          CONFIG_LOWER=$(echo "${{ matrix.config }}" | tr "[:upper:]" "[:lower:]")
          FEATURES_LOWER=$(echo "${{ matrix.feature-set }}" | tr "+" "_")
          TAG=$(printf "${{ matrix.image-template }}" "$CONFIG_LOWER" "$FEATURES_LOWER")
          echo "IMAGE_TAG=$TAG" | tee -a $GITHUB_ENV
      - name: Build and Test AMDVLK with Docker
        run: |
          docker build . --file docker/amdvlk.Dockerfile \
                         --build-arg BRANCH="${{ matrix.branch }}" \
                         --build-arg CONFIG="${{ matrix.config }}" \
                         --build-arg FEATURES="${{ matrix.feature-set }}" \
                         --build-arg GENERATOR="${{ matrix.generator }}" \
                         --tag "$IMAGE_TAG"
